/*
Project: DVD Rental Business Performance Analysis
Author: Burcu Süzer

Business Question:
Which are the top 10 most frequently rented movies?
*/

WITH movie_metrics AS (
    SELECT
        f.film_id,
        f.title AS film_title,
        COUNT(r.rental_id) AS total_rentals
    FROM
        film f
    JOIN inventory i
        ON f.film_id = i.film_id
    JOIN rental r
        ON i.inventory_id = r.inventory_id
    GROUP BY
        f.film_id,
        f.title
),
ranked_movies AS (
    SELECT
        film_id,
        film_title,
        total_rentals,
        ROW_NUMBER() OVER (ORDER BY total_rentals DESC) AS movie_rank
    FROM
        movie_metrics
)
SELECT
    movie_rank,
    film_id,
    film_title,
    total_rentals
FROM
    ranked_movies
WHERE
    movie_rank <= 10
ORDER BY
    movie_rank;


/*
Bonus Business Question:
What percentage of the total revenue is generated by the top 10 most frequently rented movies?
*/

WITH movie_metrics AS (
    SELECT
        f.film_id,
        f.title AS film_title,
        COUNT(r.rental_id) AS total_rentals,
        SUM(p.amount) AS movie_revenue
    FROM
        film f
    JOIN inventory i
        ON f.film_id = i.film_id
    JOIN rental r
        ON i.inventory_id = r.inventory_id
    JOIN payment p
        ON p.rental_id = r.rental_id
    GROUP BY
        f.film_id,
        f.title
),
ranked_movies AS (
    SELECT
        film_id,
        film_title,
        total_rentals,
        movie_revenue,
        ROW_NUMBER() OVER (ORDER BY total_rentals DESC) AS movie_rank,
        SUM(movie_revenue) OVER () AS overall_movie_revenue
    FROM
        movie_metrics
),
top10_movies AS (
    SELECT
        movie_rank,
        film_id,
        film_title,
        total_rentals,
        movie_revenue,
        overall_movie_revenue,
        ROUND(movie_revenue * 100 / overall_movie_revenue, 2) AS revenue_share_pct
    FROM
        ranked_movies
    WHERE
        movie_rank <= 10
)
SELECT
    movie_rank,
    film_id,
    film_title,
    total_rentals,
    movie_revenue,
    revenue_share_pct,
    ROUND(SUM(movie_revenue) OVER () * 100 / overall_movie_revenue, 2) AS top10_revenue_share_pct
FROM
    top10_movies
ORDER BY
    movie_rank;